package uwu.levaltru.warvilore.trashcan

import org.bukkit.NamespacedKey
import uwu.levaltru.warvilore.Warvilore

enum class Namespaces() {
    ABILITY_SAVE_PLACE,
    SOFTWARE_SAVE_PLACE,
    SOFTWARE_SAVE_ARGS_PLACE,


    INVISIBILITY_COUNTER,
    EVIL_AURA_SICKNESS,
    MANA,
    TREE_COOLDOWN,
    COOLDOWN,
    ALLOWED_NICKNAMES,
    DRANK_SOULS,
    BEFORE_NEXT_STROKE,
    BEFORE_NEXT_PRAY,
    BLOOD_SLICE_COOLDOWN,
    COLDNESS,
    CHARGE,
    CHARGES,
    REFILL,


    HALO_SPEED,
    HALO_COLOR,
    HALO_TYPE,
    HALO_SHOULD_WIGGLE,


    CUSTOM_ITEM,
    SOULBOUND,
    SOUL_IN_THE_BOTTLE,
    TIMES_BEFORE_BREAK,


    WHO_HAVE_HIT,


    SHOULD_DESPAWN,


    WORLD_ZONE_BLUR,
    WORLD_ZONE_BLUR_SPEED,
    WORLD_ZONE_APPROACHING_BLUR,
    WORLD_ZONE_DISTANCE,
    WORLD_ZONE_APPROACHING_DISTANCE,
    WORLD_ZONE_SPEED,
    WORLD_ZONE_TYPE,

    WORLD_ARE_PORTAL_ALLOWED,

    ;

    val namespace = Warvilore.namespace(this.toString())
}